# 异常分类



编译器异常和运行时



```java

package com.codertomwu.MyException;

import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;

public class MyExceptionMain {

    public static void main(String[] args) {


        // 编译异常示例
        SimpleDateFormat  sdf = new SimpleDateFormat("yy-MM-dd");
        Date date = null;
        try {
            date = sdf.parse("18-11-03");
        } catch (ParseException e) {
            e.printStackTrace();
        }
        System.out.println(date);


        // 运行时
        int[] arr = {1,2,3};
        System.out.println(arr[3]);


    }
}


```







# 异常关键字



java 异常处理的五个关键字：**try**，**catch**，**throw**，**throws**，





# 异常处理throw



在编写程序时,我们必须要考虑程序出现问题的情况。比如,在定义方法时,方法需要接受参数。那么,当调用方法使用接受到的参数时,首先需要先对参数数据进行合法的判断,数据若不合法,就应该告诉调用者,传递合法的数据进来。这时需要使用抛出异常的方式来告诉调用者。

在java中,提供了一个throw关键字，它用来抛出一个指定的异常对象。那么,抛出一个异常具体如何操作呢?

1.创建一个异常对象。 封装一些提示信息(信息可以自己编写)。

2.需要将这个异常对象告知给调用者。怎么告知呢?怎么将这个异常对象传递到调用者处呢?通过关键字throw就可以完成。throw 异常对象。

  throw用在方法内,用来抛出一个异常对象,将这个异常对象传递到调用者处,并结束当前方法的执行。



**使用格式**

```java

throw new 异常类名（参数）；

```





```java
  throw 关键字作用:

  可以使用throw关键字在指定的方法中抛出指定的昇常使用格式:

  throw new XXException(“异常产生的原因”);
  注意:

  1. throw 关键字必須写在方法的内部

  2. throw 关键字后边 new 的対象必須是 Exception 或者Exception的子类
  3. throw 关键字抛出指定的异常対象,我们就必須处理这个异常対象

  throw  关键字后边創建的是Runtime Exception或者是RuntimeException的子类对象,我们可以不处理,默认交給JVM处理(打印异常対象,中断程序)
  throw 关键字后边创建的是编译异常(写代碼的吋候报錯),我們就必須処理这个异常,要么 throws ,要么 try...catch
```




#  throws 声明的异常如果存在父子继承关系我们可以只福throws父类



```java

public static int  getElement(int[] arr, int index) throws Exception{

        if (arr == null){

            throw new NullPointerException("传递的数组的值是null");
        }
        int ele = arr[index];

        return ele;
    }

```







# 捕获异常



```java

try{
   // 程序代码
}catch(异常类型1 异常的变量名1){
  // 程序代码
}catch(异常类型2 异常的变量名2){
  // 程序代码
}catch(异常类型2 异常的变量名2){
  // 程序代码
}

```





```java

try
{
  file = new FileInputStream(fileName);
  x = (byte) file.read();
}catch(IOException i)
{
  i.printStackTrace();
  return -1;
}catch(FileNotFoundException f) //Not valid!
{
  f.printStackTrace();
  return -1;
}

```

# finally

finally 关键字用来创建在 try 代码块后面执行的代码块。

无论是否发生异常，finally 代码块中的代码总会被执行。

在 finally 代码块中，可以运行清理类型等收尾善后性质的语句。

finally 代码块出现在 catch 代码块最后，语法如下：

```java

try{
  // 程序代码
}catch(异常类型1 异常的变量名1){
  // 程序代码
}catch(异常类型2 异常的变量名2){
  // 程序代码
}finally{
  // 程序代码
}

```





```java

package com.codertomwu.MyException;

// 如果finally有return 语句， 永远返回finally中 的结果， 并避免
public class MyFinallyTest {


    public static void main(String[] args) {


        System.out.println(getNum());
    }

    public static int getNum(){

        int a = 20;

//        return a;
        try {
            int[] arr = {1,2,3};
            System.out.println(arr[3]);
        }catch (Exception e){

        }finally {

            a = 33;
            return a;
        }

    }
}


```





# 多个异常

多个异常使用捕获又该如何处理呢?

1.多个异常分别处理。
2.多个异常一次捕获，多次处理。

3.多个异常一次捕获一次处理。





```java

package com.codertomwu.MyException;

import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.LinkedList;
import java.util.List;

public class MyExceptionMain {

    public static void main(String[] args) throws Exception {


        // 编译异常示例
//        SimpleDateFormat  sdf = new SimpleDateFormat("yy-MM-dd");
//        Date date = null;
//        try {
//            date = sdf.parse("18-11-03");
//        } catch (ParseException e) {
//            e.printStackTrace();
//        }
//        System.out.println(date);
//
//
//        // 运行时
//        int[] arr = {1,2,3};
////        System.out.println(arr[3]);
//
//
//        int[] arr2 = null;
//        getElement(arr2,2);

        excepationT3();

    }


    public static int  getElement(int[] arr, int index) throws Exception{

        if (arr == null){

            throw new NullPointerException("传递的数组的值是null");
        }
        int ele = arr[index];

        return ele;
    }




    public static void excepationT1(){

        try {
            int[] arr = {1,2,3};
            System.out.println(arr[3]);
        }catch (ArrayIndexOutOfBoundsException e){

            System.out.println(e);
        }

        try {
            List<Integer> list = List.of(1,2,3);
            System.out.println(list.get(3));
        }catch (IndexOutOfBoundsException e){
            System.out.println(e);
        }
    }
// 多个异常分别处理
    public static void excepationT2(){

        try {

            int[] arr = {1,2,3};
            System.out.println(arr[3]);

            List<Integer> list = List.of(1,2,3);
            System.out.println(list.get(3));
            /**
             * 异常有子父类关系子类必须写父类上面
             * ArrayIndexOutOfBoundsException继承IndexOutOfBoundsException
             * 所以ArrayIndexOutOfBoundsException写前面
             * */
        }catch (ArrayIndexOutOfBoundsException e){
            System.out.println(e);
        }catch (IndexOutOfBoundsException e){
            System.out.println(e);
        }

    }


//    2.多个异常一次捕获，多次处理。

    public static void excepationT3(){

        try {

            int[] arr = {1,2,3};
            System.out.println(arr[3]);

            List<Integer> list = List.of(1,2,3);
            System.out.println(list.get(3));

        }catch (IndexOutOfBoundsException e){
            System.out.println(e);
        }

    }


}


```



运行时异常被抛出可以不处理， 即不捕获也不声明抛出。。







# 父类中方法的异常子类



父子类的异常：

- 如果父类抛出了多个异常， 子类重写父类方法时， 抛出和父类相同的异常或者是父类异常的子类或者不抛出
- 父类方法没有抛出异常， 子类重写父类方法时也不可以抛出异常， 只能捕获处理不能声明抛出。。。



**父类 异常什么样子类就什么样**





# 自定义异常类



```java

package com.codertomwu.MyException;

/**
 * 自定义异常类
 *注意：
 *自定义异常类一般都是Exception结尾。。。
 * 自定义异常类必须继承Exception(编译异常)或者继承RuntimeException（运行时异常）
 *
 * */
public class RegisterException extends Exception/** 或者继承RuntimeException */  {

    public RegisterException() {
    }

    public RegisterException(String s) {
        super(s);
    }
}


```





